"""empty message

Revision ID: 31a05f14ef3
Revises: None
Create Date: 2015-12-13 17:01:37.297578

"""

# revision identifiers, used by Alembic.
revision = '31a05f14ef3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('client', sa.String(length=255), nullable=False))
    op.add_column('project', sa.Column('subProjectName', sa.String(length=255), nullable=True))
    op.drop_constraint('project_user_id_fkey', 'project', type_='foreignkey')
    op.drop_constraint('project_customer_id_fkey', 'project', type_='foreignkey')
    op.drop_column('project', 'customer_id')
    op.drop_column('project', 'scripts')
    op.drop_column('project', 'user_id')
    op.drop_column('project', 'projectReferenceId')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('projectReferenceId', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('project', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('scripts', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('project_customer_id_fkey', 'project', 'customer', ['customer_id'], ['id'])
    op.create_foreign_key('project_user_id_fkey', 'project', 'user', ['user_id'], ['id'])
    op.drop_column('project', 'subProjectName')
    op.drop_column('project', 'client')
    ### end Alembic commands ###
