"""empty message

Revision ID: 54c1740ada63
Revises: None
Create Date: 2015-11-12 18:34:26.454489

"""

# revision identifiers, used by Alembic.
revision = '54c1740ada63'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('function', sa.String(length=255), nullable=True))
    op.add_column('customer', sa.Column('landline', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'landline')
    op.drop_column('customer', 'function')
    ### end Alembic commands ###
